version: '3.4'
services:

    app:
        build:
          context: .
          dockerfile: ./docker/app/Dockerfile
          target: app-production
        volumes:
          # Mount credentials file into container
          - ./.env:/app/.env
          # For development, use the following volume mount instead:
          # - .:/app
        ports:
          - 8090:80

